-- MySQL Script generated by MySQL Workbench
-- Thu Apr 25 15:27:52 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema landmonkdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema landmonkdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `landmonkdb` DEFAULT CHARACTER SET utf8 ;
USE `landmonkdb` ;

-- -----------------------------------------------------
-- Table `landmonkdb`.`Properties`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `landmonkdb`.`Properties` ;

CREATE TABLE IF NOT EXISTS `landmonkdb`.`Properties` (
  `PropertyId` INT NOT NULL AUTO_INCREMENT,
  `PropertyName` VARCHAR(100) NOT NULL,
  `Address` VARCHAR(100) NOT NULL,
  `City` VARCHAR(50) NOT NULL,
  `State` CHAR(2) NOT NULL,
  `ZipCode` CHAR(9) NOT NULL,
  PRIMARY KEY (`PropertyId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `landmonkdb`.`Units`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `landmonkdb`.`Units` ;

CREATE TABLE IF NOT EXISTS `landmonkdb`.`Units` (
  `UnitId` INT NOT NULL AUTO_INCREMENT,
  `UnitName` VARCHAR(100) NOT NULL,
  `BedroomCount` INT NOT NULL,
  `BathroomCount` FLOAT NOT NULL,
  `SquareFootage` INT NOT NULL,
  `PropertyId` INT NOT NULL,
  PRIMARY KEY (`UnitId`),
  INDEX `fk_Units_Properties_idx` (`PropertyId` ASC) VISIBLE,
  CONSTRAINT `fk_Units_Properties`
    FOREIGN KEY (`PropertyId`)
    REFERENCES `landmonkdb`.`Properties` (`PropertyId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `landmonkdb`.`Tenants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `landmonkdb`.`Tenants` ;

CREATE TABLE IF NOT EXISTS `landmonkdb`.`Tenants` (
  `TenantId` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `CellPhone` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`TenantId`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
